server:
  port: 8088
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8192

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zhou?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
      timeout: 1000           # 连接超时时间（毫秒）

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml

#showSql
logging:
  level:
    com:
      example:
        mapper : debug