/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zhou.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)")
public enum UserVerifyType implements org.apache.thrift.TEnum {
  NOT_VERIFIED(0),
  NORMAL_VERIFY(1),
  BRAND_VERIFY(2),
  ORG_VERIFY(3),
  ENT_VERIFY(4);

  private final int value;

  private UserVerifyType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static UserVerifyType findByValue(int value) { 
    switch (value) {
      case 0:
        return NOT_VERIFIED;
      case 1:
        return NORMAL_VERIFY;
      case 2:
        return BRAND_VERIFY;
      case 3:
        return ORG_VERIFY;
      case 4:
        return ENT_VERIFY;
      default:
        return null;
    }
  }
}
