/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zhou.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)")
public enum VerifyStatus implements org.apache.thrift.TEnum {
  NOT_VERIFIED(0),
  VERIFIED(1),
  RETURN(2),
  AUDITING(3);

  private final int value;

  private VerifyStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static VerifyStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return NOT_VERIFIED;
      case 1:
        return VERIFIED;
      case 2:
        return RETURN;
      case 3:
        return AUDITING;
      default:
        return null;
    }
  }
}
